name: Build Docker Image and Trigger METplus Workflow
on:
  push: null
env:
  DOCKERHUB_REPO: dtcenter/met-dev
jobs:
  build_met_docker:
    runs-on: ubuntu-latest
    name: Handle Docker Image
    steps:
    - uses: actions/checkout@v4
    - name: Get branch name
      id: get_branch_name
      run: echo branch_name=${GITHUB_REF#refs/heads/} >> $GITHUB_OUTPUT
    - name: Build Docker Image
      run: .github/jobs/build_docker_image.sh
      env:
        SOURCE_BRANCH: ${{ steps.get_branch_name.outputs.branch_name }}-lite
        MET_BASE_REPO: met-base
        MET_BASE_TAG: v3.3
    - name: Push Docker Image
      run: .github/jobs/push_docker_image.sh
      env:
        SOURCE_BRANCH: ${{ steps.get_branch_name.outputs.branch_name }}-lite
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - uses: dtcenter/metplus-action-trigger-use-cases@v1
      with:
        token: ${{ secrets.METPLUS_BOT_TOKEN }}
